// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aofybcurppbcnenreepz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZnliY3VycHBiY25lbnJlZXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NTE5MTksImV4cCI6MjA4ODMyNzkxOX0.Bxldy9y8yFlQ2Zz8erRQiuTqJqlKF7R-gcZKQP-Aqag";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);